<a href="https://colab.research.google.com/github/2403a52009-bot/NLP/blob/main/nlp_asn_14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Lab14.4_NER_spaCy_HF_Name_RollNo

## Assignment 14.4 – Named Entity Recognition (NER)
Implement NER using spaCy and Hugging Face Transformers and compare results.

## STEP 1 & 2 — Install Required Libraries

In [1]:

!pip install spacy transformers torch pandas seaborn --quiet
!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 38.4 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

## STEP 3 — Import Libraries

In [2]:

import spacy
from spacy import displacy
from transformers import pipeline, AutoTokenizer, AutoModelForTokenClassification
import torch
import pandas as pd


spaCy → Pretrained NLP pipeline  
Transformers → Contextual NER model  
torch → Backend for deep learning  
pandas → Data handling and tables

## STEP 4 — Load spaCy Model

In [3]:

nlp = spacy.load("en_core_web_sm")


spaCy pipeline includes:
- Tokenizer
- POS Tagger
- Dependency Parser
- Named Entity Recognizer

## STEP 5 — Sample Sentences

In [4]:

sentences = [
    "Apple CEO Tim Cook announced new products in California.",
    "Elon Musk visited India to meet Prime Minister Narendra Modi.",
    "Microsoft acquired Activision Blizzard for $68 billion.",
    "The FIFA World Cup was held in Qatar in 2022.",
    "Google launched a new AI model in New York."
]

## STEP 6 — Apply spaCy NER

In [5]:

spacy_results = []

for sentence in sentences:
    doc = nlp(sentence)
    for ent in doc.ents:
        print(f"Sentence: {sentence}")
        print(f"Entity: {ent.text}, Label: {ent.label_}")
        print("-"*40)
        spacy_results.append([sentence, ent.text, ent.label_])

Sentence: Apple CEO Tim Cook announced new products in California.
Entity: Apple, Label: ORG
----------------------------------------
Sentence: Apple CEO Tim Cook announced new products in California.
Entity: Tim Cook, Label: PERSON
----------------------------------------
Sentence: Apple CEO Tim Cook announced new products in California.
Entity: California, Label: GPE
----------------------------------------
Sentence: Elon Musk visited India to meet Prime Minister Narendra Modi.
Entity: Elon Musk, Label: PERSON
----------------------------------------
Sentence: Elon Musk visited India to meet Prime Minister Narendra Modi.
Entity: India, Label: GPE
----------------------------------------
Sentence: Elon Musk visited India to meet Prime Minister Narendra Modi.
Entity: Narendra Modi, Label: PERSON
----------------------------------------
Sentence: Microsoft acquired Activision Blizzard for $68 billion.
Entity: Microsoft, Label: ORG
----------------------------------------
Sentence: Microsoft acquired Activision Blizzard for $68 billion.
Entity: Activision Blizzard, Label: PERSON
----------------------------------------
Sentence: Microsoft acquired Activision Blizzard for $68 billion.
Entity: $68 billion, Label: MONEY
----------------------------------------
Sentence: The FIFA World Cup was held in Qatar in 2022.
Entity: World Cup, Label: EVENT
----------------------------------------
Sentence: The FIFA World Cup was held in Qatar in 2022.
Entity: Qatar, Label: GPE
----------------------------------------
Sentence: The FIFA World Cup was held in Qatar in 2022.
Entity: 2022, Label: DATE
----------------------------------------
Sentence: Google launched a new AI model in New York.
Entity: Google, Label: ORG
----------------------------------------
Sentence: Google launched a new AI model in New York.
Entity: AI, Label: GPE
----------------------------------------
Sentence: Google launched a new AI model in New York.
Entity: New York, Label: GPE
----------------------------------------

## STEP 7 — Store spaCy Results in DataFrame

In [6]:

spacy_df = pd.DataFrame(spacy_results, columns=["Sentence", "Entity", "Label"])
spacy_df

,Sentence,Entity,Label
0,Apple CEO Tim Cook announced new products in C...,Apple,ORG
1,Apple CEO Tim Cook announced new products in C...,Tim Cook,PERSON
2,Apple CEO Tim Cook announced new products in C...,California,GPE
3,Elon Musk visited India to meet Prime Minister...,Elon Musk,PERSON
4,Elon Musk visited India to meet Prime Minister...,India,GPE
5,Elon Musk visited India to meet Prime Minister...,Narendra Modi,PERSON
6,Microsoft acquired Activision Blizzard for $68...,Microsoft,ORG
7,Microsoft acquired Activision Blizzard for $68...,Activision Blizzard,PERSON
8,Microsoft acquired Activision Blizzard for $68...,$68 billion,MONEY
9,The FIFA World Cup was held in Qatar in 2022.,World Cup,EVENT
10,The FIFA World Cup was held in Qatar in 2022.,Qatar,GPE
11,The FIFA World Cup was held in Qatar in 2022.,2022,DATE
12,Google launched a new AI model in New York.,Google,ORG
13,Google launched a new AI model in New York.,AI,GPE
14,Google launched a new AI model in New York.,New York,GPE

## STEP 8 — Visualize Entities (Optional)

In [7]:

for sentence in sentences:
    doc = nlp(sentence)
    displacy.render(doc, style="ent", jupyter=True)

## STEP 9 — Load Hugging Face NER Model

In [8]:

tokenizer = AutoTokenizer.from_pretrained("dslim/bert-base-NER")
model = AutoModelForTokenClassification.from_pretrained("dslim/bert-base-NER")
ner_pipeline = pipeline("ner", model=model, tokenizer=tokenizer)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/829 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/59.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/433M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForTokenClassification LOAD REPORT from: dslim/bert-base-NER
Key                      | Status     |  |
-------------------------+------------+--+-
bert.pooler.dense.bias   | UNEXPECTED |  |
bert.pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


Token classification assigns a label to each token.
Transformers use self-attention for contextual understanding.

## STEP 10 — Apply Transformer NER

In [9]:

hf_results = []

for sentence in sentences:
    outputs = ner_pipeline(sentence)
    print(f"Sentence: {sentence}")
    for entity in outputs:
        print(entity)
        hf_results.append([sentence, entity["word"], entity["entity"], entity["score"]])
    print("-"*40)

Sentence: Apple CEO Tim Cook announced new products in California.
{'entity': 'B-ORG', 'score': np.float32(0.9988612), 'index': 1, 'word': 'Apple', 'start': 0, 'end': 5}
{'entity': 'B-PER', 'score': np.float32(0.99973744), 'index': 3, 'word': 'Tim', 'start': 10, 'end': 13}
{'entity': 'I-PER', 'score': np.float32(0.99978286), 'index': 4, 'word': 'Cook', 'start': 14, 'end': 18}
{'entity': 'B-LOC', 'score': np.float32(0.99974674), 'index': 9, 'word': 'California', 'start': 45, 'end': 55}
----------------------------------------
Sentence: Elon Musk visited India to meet Prime Minister Narendra Modi.
{'entity': 'B-PER', 'score': np.float32(0.9983015), 'index': 1, 'word': 'El', 'start': 0, 'end': 2}
{'entity': 'B-PER', 'score': np.float32(0.7953468), 'index': 2, 'word': '##on', 'start': 2, 'end': 4}
{'entity': 'I-PER', 'score': np.float32(0.99855417), 'index': 3, 'word': 'Mu', 'start': 5, 'end': 7}
{'entity': 'I-PER', 'score': np.float32(0.923724), 'index': 4, 'word': '##sk', 'start': 7, 'end': 9}
{'entity': 'B-LOC', 'score': np.float32(0.99982184), 'index': 6, 'word': 'India', 'start': 18, 'end': 23}
{'entity': 'B-PER', 'score': np.float32(0.999481), 'index': 11, 'word': 'Na', 'start': 47, 'end': 49}
{'entity': 'B-PER', 'score': np.float32(0.6377561), 'index': 12, 'word': '##ren', 'start': 49, 'end': 52}
{'entity': 'I-PER', 'score': np.float32(0.75229746), 'index': 13, 'word': '##dra', 'start': 52, 'end': 55}
{'entity': 'I-PER', 'score': np.float32(0.99945456), 'index': 14, 'word': 'Mo', 'start': 56, 'end': 58}
{'entity': 'I-PER', 'score': np.float32(0.8885579), 'index': 15, 'word': '##di', 'start': 58, 'end': 60}
----------------------------------------
Sentence: Microsoft acquired Activision Blizzard for $68 billion.
{'entity': 'B-ORG', 'score': np.float32(0.99886936), 'index': 1, 'word': 'Microsoft', 'start': 0, 'end': 9}
{'entity': 'B-ORG', 'score': np.float32(0.999297), 'index': 3, 'word': 'Act', 'start': 19, 'end': 22}
{'entity': 'I-ORG', 'score': np.float32(0.9980432), 'index': 4, 'word': '##ivision', 'start': 22, 'end': 29}
{'entity': 'I-ORG', 'score': np.float32(0.9992731), 'index': 5, 'word': 'B', 'start': 30, 'end': 31}
{'entity': 'I-ORG', 'score': np.float32(0.9985246), 'index': 6, 'word': '##lizzard', 'start': 31, 'end': 38}
----------------------------------------
Sentence: The FIFA World Cup was held in Qatar in 2022.
{'entity': 'B-MISC', 'score': np.float32(0.9966832), 'index': 2, 'word': 'FIFA', 'start': 4, 'end': 8}
{'entity': 'I-MISC', 'score': np.float32(0.99603796), 'index': 3, 'word': 'World', 'start': 9, 'end': 14}
{'entity': 'I-MISC', 'score': np.float32(0.99851876), 'index': 4, 'word': 'Cup', 'start': 15, 'end': 18}
{'entity': 'B-LOC', 'score': np.float32(0.9997582), 'index': 8, 'word': 'Qatar', 'start': 31, 'end': 36}
----------------------------------------
Sentence: Google launched a new AI model in New York.
{'entity': 'B-ORG', 'score': np.float32(0.9980757), 'index': 1, 'word': 'Google', 'start': 0, 'end': 6}
{'entity': 'B-MISC', 'score': np.float32(0.9938427), 'index': 5, 'word': 'AI', 'start': 22, 'end': 24}
{'entity': 'B-LOC', 'score': np.float32(0.99957675), 'index': 8, 'word': 'New', 'start': 34, 'end': 37}
{'entity': 'I-LOC', 'score': np.float32(0.99949455), 'index': 9, 'word': 'York', 'start': 38, 'end': 42}
----------------------------------------

## STEP 11 — Clean Transformer Output

In [10]:

cleaned_results = []

for sentence, word, label, score in hf_results:
    clean_word = word.replace("##", "")
    cleaned_results.append([sentence, clean_word, label, score])

hf_df = pd.DataFrame(cleaned_results, columns=["Sentence", "Entity", "Label", "Confidence"])
hf_df

,Sentence,Entity,Label,Confidence
0,Apple CEO Tim Cook announced new products in C...,Apple,B-ORG,0.998861
1,Apple CEO Tim Cook announced new products in C...,Tim,B-PER,0.999737
2,Apple CEO Tim Cook announced new products in C...,Cook,I-PER,0.999783
3,Apple CEO Tim Cook announced new products in C...,California,B-LOC,0.999747
4,Elon Musk visited India to meet Prime Minister...,El,B-PER,0.998302
5,Elon Musk visited India to meet Prime Minister...,on,B-PER,0.795347
6,Elon Musk visited India to meet Prime Minister...,Mu,I-PER,0.998554
7,Elon Musk visited India to meet Prime Minister...,sk,I-PER,0.923724
8,Elon Musk visited India to meet Prime Minister...,India,B-LOC,0.999822
9,Elon Musk visited India to meet Prime Minister...,Na,B-PER,0.999481
10,Elon Musk visited India to meet Prime Minister...,ren,B-PER,0.637756
11,Elon Musk visited India to meet Prime Minister...,dra,I-PER,0.752297
12,Elon Musk visited India to meet Prime Minister...,Mo,I-PER,0.999455
13,Elon Musk visited India to meet Prime Minister...,di,I-PER,0.888558
14,Microsoft acquired Activision Blizzard for $68...,Microsoft,B-ORG,0.998869
15,Microsoft acquired Activision Blizzard for $68...,Act,B-ORG,0.999297
16,Microsoft acquired Activision Blizzard for $68...,ivision,I-ORG,0.998043
17,Microsoft acquired Activision Blizzard for $68...,B,I-ORG,0.999273
18,Microsoft acquired Activision Blizzard for $68...,lizzard,I-ORG,0.998525
19,The FIFA World Cup was held in Qatar in 2022.,FIFA,B-MISC,0.996683
20,The FIFA World Cup was held in Qatar in 2022.,World,I-MISC,0.996038
21,The FIFA World Cup was held in Qatar in 2022.,Cup,I-MISC,0.998519
22,The FIFA World Cup was held in Qatar in 2022.,Qatar,B-LOC,0.999758
23,Google launched a new AI model in New York.,Google,B-ORG,0.998076
24,Google launched a new AI model in New York.,AI,B-MISC,0.993843
25,Google launched a new AI model in New York.,New,B-LOC,0.999577
26,Google launched a new AI model in New York.,York,I-LOC,0.999495


## STEP 12 — Comparison Table

| Feature | spaCy | Hugging Face |
|----------|--------|--------------|
| Model Type | Statistical | Transformer |
| Speed | Fast | Slower |
| Context Handling | Limited | Strong |
| Confidence Score | No | Yes |
| Accuracy | Moderate | High |


## STEP 13 — Result Analysis

Transformers detected more contextual entities and provided confidence scores.
spaCy was faster and lightweight.
Transformer handled complex names better.
However, it required more computational power.


## STEP 14 — Error Analysis

Example possible errors:
1. Organization names split into subwords.
2. Ambiguous words misclassified.
3. Rare entities not detected.